services:
  nginx-ssl:
    image: nginx:latest
    volumes:
      - ./nginx/nginx-ssl.conf:/etc/nginx/conf.d/default.conf
      - ./.certbot/www/:/var/www/certbot:ro
    networks:
      - nginx-network
    ports:
      - 80:80
      - 443:443
  certbot:
    image: certbot/certbot
    volumes:
      - ./.certbot/www/:/var/www/certbot/:rw
      - ./.certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - nginx-network
networks:
  nginx-network:
      driver: bridge
