services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./.mysql/data:/var/lib/mysql
    networks:
      - api-miseenscreen
  redis:
    image: redis:6.2-alpine
    environment:
      - REDIS_PASSWORD=admin
    volumes:
      - /.redis/d–∞ta:/root/redis
      - /.redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - api-miseenscreen
  php-fpm:
    build: .
    restart: always
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/app
    volumes:
      - ./.symfony/jwt:/var/www/html/config/jwt
      - ./.storage:/var/www/html/.storage  
    networks:
      - api-miseenscreen
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
      - ./.certbot/conf:/etc/nginx/certbot
    environment:
      - PROJECT_DOMAIN=miseenscreen.com
    ports:
      - 80:80
      - 443:443 
    networks:
      - api-miseenscreen

networks:
  api-miseenscreen:
    name: miseenscreen
    external: true
